/** WHD request types shown as default tag suggestions (all 27 from WHD instance). */
export const DEFAULT_TAG_SUGGESTIONS = [
  'ACCOUNT (u-,r-,b-number,...)',
  'ADMINISTRATIVE RIGHTS',
  'ARTICLE on LOAN',
  'CERTIFICATE ISSUE',
  'COLLABORATION/COMMUNICATION',
  'COMPUTER and ACCESSORIES',
  'FACILITEITEN',
  'FORWARD FROM IT DEPARTMENT',
  'REMOTE DESKTOP ACCESS',
  'IVANTI VPN',
  'LINUX',
  'MAILBOX (Outlook, Adm. Email...)',
  'Multi Factor Authentication (MFA)',
  'NEED A HARDPHONE (CAP)',
  'NEED A PHONE NUMBER',
  'NEED A SOFTPHONE (USB)',
  'NETWORK (Wired / Wireless)',
  'PERIPHERALS (keyboard, mouse, headset,...)',
  'PHONE ISSUE (General)',
  'PRINTER',
  'REDCAP',
  'REMOTE ACCESS',
  'Request by mail',
  'SHINY R App Hosting',
  'SOFTWARE',
  'SOFTWARE BLOCKED by AppLocker',
  'WEBSITE & WEB APPS',
]
